export enum AuthActionType {
  ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS',
  ON_REGISTER = 'ON_REGISTER',
  ON_LOGGING = 'ON_LOGGING',
  ON_ERROR = 'ON_ERROR',
  ON_LOGOUT = 'ON_LOGOUT',
  ON_LOGGING_BY_TOKEN = 'ON_LOGGING_BY_TOKEN',
}
